// ============================================================
// XEQUE MATE STUDIO — Mock Data para Demonstração
// ============================================================

import { Artist, Client, KanbanCard, Transaction, Session } from './types'

export const mockArtists: Artist[] = [
  {
    id: 'a1',
    artisticName: 'MC Sombra',
    realName: 'Lucas Ferreira',
    genre: 'rap',
    status: 'ativo',
    phone: '(11) 99999-1111',
    email: 'sombra@xequemate.com',
    instagram: '@mcsombra',
    spotify: 'MC Sombra',
    bio: 'Rapper paulistano com foco em letras conscientes e batidas pesadas.',
    projectCount: 12,
    totalRevenue: 8400,
    joinedAt: '2023-03-15',
  },
  {
    id: 'a2',
    artisticName: 'MC Bielzinho',
    realName: 'Gabriel Santos',
    genre: 'funk',
    status: 'ativo',
    phone: '(11) 99999-2222',
    email: 'bielzinho@xequemate.com',
    instagram: '@mcbielzinho',
    youtube: 'MC Bielzinho Oficial',
    bio: 'Hitmaker do funk consciente e mandelão da capital.',
    projectCount: 8,
    totalRevenue: 6200,
    joinedAt: '2023-07-20',
  },
  {
    id: 'a3',
    artisticName: 'DJ Pedro MPC',
    realName: 'Pedro Henrique',
    genre: 'dj',
    status: 'ativo',
    phone: '(11) 99999-3333',
    email: 'djpedro@xequemate.com',
    instagram: '@djpedrompc',
    bio: 'Produtor e DJ residente, especialista em beatmaking e montagens.',
    projectCount: 15,
    totalRevenue: 9800,
    joinedAt: '2024-01-10',
  },
  {
    id: 'a4',
    artisticName: 'MC Menor da Leste',
    realName: 'Diego Mateus',
    genre: 'funk',
    status: 'ativo',
    phone: '(11) 99999-4444',
    email: 'menordaleste@email.com',
    instagram: '@menordaleste',
    projectCount: 6,
    totalRevenue: 4200,
    joinedAt: '2024-04-05',
  },
  {
    id: 'a5',
    artisticName: 'Voz da Rua',
    realName: 'Thiago Lima',
    genre: 'rap',
    status: 'ativo',
    phone: '(11) 99999-5555',
    email: 'vozdarua@email.com',
    instagram: '@vozdarua',
    spotify: 'Voz da Rua',
    youtube: 'Voz da Rua TV',
    bio: 'MC veterano da cena underground de São Paulo.',
    projectCount: 20,
    totalRevenue: 14500,
    joinedAt: '2022-11-01',
  },
]

export const mockClients: Client[] = [
  {
    id: 'c1',
    name: 'Pedro Almeida',
    phone: '(11) 98888-1111',
    email: 'pedro@email.com',
    clientType: 'externo',
    totalSessions: 4,
    pendingBalance: 500,
    totalSpent: 2000,
    createdAt: '2024-02-10',
  },
  {
    id: 'c2',
    name: 'Ana Cristina',
    phone: '(11) 98888-2222',
    email: 'ana@email.com',
    clientType: 'externo',
    instagram: '@anacristina',
    totalSessions: 2,
    pendingBalance: 0,
    totalSpent: 900,
    createdAt: '2024-03-22',
  },
  {
    id: 'c3',
    name: 'Grupo Nova Era',
    phone: '(11) 98888-3333',
    clientType: 'externo',
    totalSessions: 7,
    pendingBalance: 1200,
    totalSpent: 5400,
    createdAt: '2023-09-15',
  },
  {
    id: 'c4',
    name: 'Felipe Costa',
    phone: '(11) 98888-4444',
    email: 'felipe@email.com',
    clientType: 'externo',
    totalSessions: 1,
    pendingBalance: 0,
    totalSpent: 450,
    createdAt: '2024-06-01',
  },
  {
    id: 'c5',
    name: 'Coletivo Norte',
    phone: '(11) 98888-5555',
    clientType: 'externo',
    instagram: '@coletivanorte',
    totalSessions: 10,
    pendingBalance: 800,
    totalSpent: 7200,
    notes: 'Cliente VIP — sempre traz projetos grandes.',
    createdAt: '2023-05-20',
  },
]

export const mockKanbanCards: KanbanCard[] = [
  {
    id: 'k1',
    trackName: 'Invicto',
    artistName: 'MC Sombra',
    stage: 'gravacao',
    priority: 'urgente',
    entryDate: '2024-06-28',
    deadline: '2024-07-05',
    daysInStage: 5,
    notes: 'Falta gravar o feat com Bia Flow',
  },
  {
    id: 'k2',
    trackName: 'Madrugada',
    artistName: 'Bia Flow',
    stage: 'mix',
    priority: 'normal',
    entryDate: '2024-06-20',
    deadline: '2024-07-10',
    daysInStage: 3,
  },
  {
    id: 'k3',
    trackName: 'Kraken Mode',
    artistName: 'Kraken',
    stage: 'master',
    priority: 'normal',
    entryDate: '2024-06-15',
    daysInStage: 2,
  },
  {
    id: 'k4',
    trackName: 'Favela Vive',
    artistName: 'Voz da Rua',
    stage: 'entregue',
    priority: 'normal',
    entryDate: '2024-06-01',
    daysInStage: 0,
  },
  {
    id: 'k5',
    trackName: 'Tipo Assim',
    artistName: 'Dupla Prime',
    stage: 'recall',
    priority: 'espera',
    entryDate: '2024-06-25',
    daysInStage: 8,
    notes: 'Artista pediu ajuste no refrão',
  },
  {
    id: 'k6',
    trackName: 'Noite Alta',
    artistName: 'MC Sombra',
    stage: 'gravacao',
    priority: 'normal',
    entryDate: '2024-07-01',
    daysInStage: 2,
  },
]

const now = new Date()
const months = ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun']

export const mockTransactions: Transaction[] = [
  {
    id: 't1', type: 'receita', category: 'gravacao',
    description: 'Sessão de gravação - Pedro Almeida', amount: 500,
    clientId: 'c1', date: '2024-06-30', createdAt: '2024-06-30',
  },
  {
    id: 't2', type: 'receita', category: 'mix',
    description: 'Mix - Madrugada (Bia Flow)', amount: 800,
    artistId: 'a2', date: '2024-06-29', createdAt: '2024-06-29',
  },
  {
    id: 't3', type: 'receita', category: 'master',
    description: 'Master - Kraken Mode', amount: 600,
    artistId: 'a3', date: '2024-06-28', createdAt: '2024-06-28',
  },
  {
    id: 't4', type: 'despesa', category: 'equipamento',
    description: 'Cabo XLR e pop filter', amount: 280,
    date: '2024-06-27', createdAt: '2024-06-27',
  },
  {
    id: 't5', type: 'despesa', category: 'aluguel',
    description: 'Aluguel do estúdio - Julho', amount: 3500,
    date: '2024-06-25', createdAt: '2024-06-25',
  },
  {
    id: 't6', type: 'receita', category: 'producao',
    description: 'Beat produzido - Coletivo Norte', amount: 1200,
    clientId: 'c5', date: '2024-06-24', createdAt: '2024-06-24',
  },
  {
    id: 't7', type: 'receita', category: 'gravacao',
    description: 'Sessão gravação - Grupo Nova Era', amount: 900,
    clientId: 'c3', date: '2024-06-22', createdAt: '2024-06-22',
  },
  {
    id: 't8', type: 'despesa', category: 'marketing',
    description: 'Impulsionamento redes sociais', amount: 400,
    date: '2024-06-20', createdAt: '2024-06-20',
  },
  {
    id: 't9', type: 'receita', category: 'recall',
    description: 'Recall sessão - Ana Cristina', amount: 300,
    clientId: 'c2', date: '2024-06-18', createdAt: '2024-06-18',
  },
  {
    id: 't10', type: 'receita', category: 'mix',
    description: 'Mix + Master combo - Voz da Rua', amount: 1400,
    artistId: 'a5', date: '2024-06-15', createdAt: '2024-06-15',
  },
]

export const mockSessions: Session[] = [
  {
    id: 's1',
    title: 'Gravação Invicto',
    clientId: 'a1',
    clientName: 'MC Sombra',
    serviceType: 'gravacao',
    status: 'confirmado',
    date: '2024-07-04',
    startTime: '14:00',
    endTime: '18:00',
    value: 600,
    createdAt: '2024-07-01',
  },
  {
    id: 's2',
    title: 'Mix Madrugada',
    clientId: 'a2',
    clientName: 'Bia Flow',
    serviceType: 'mix',
    status: 'confirmado',
    date: '2024-07-05',
    startTime: '10:00',
    endTime: '13:00',
    value: 400,
    createdAt: '2024-07-01',
  },
  {
    id: 's3',
    title: 'Sessão produção',
    clientId: 'c3',
    clientName: 'Grupo Nova Era',
    serviceType: 'producao',
    status: 'pendente',
    date: '2024-07-06',
    startTime: '15:00',
    endTime: '20:00',
    value: 1000,
    notes: 'Aguardando confirmação do grupo',
    createdAt: '2024-07-02',
  },
  {
    id: 's4',
    title: 'Master Kraken Mode',
    clientId: 'a3',
    clientName: 'Kraken',
    serviceType: 'master',
    status: 'concluido',
    date: '2024-07-03',
    startTime: '09:00',
    endTime: '11:00',
    value: 350,
    createdAt: '2024-07-01',
  },
]
